### ISSUE TITLE
Kaspad not synced induces miner panic error

### ISSUE THREAD

**Issue by twkrol** [tmrlvi/kaspa-miner#14]
From time to time my kaspad is out of sync, then the linux miner (under hiveos) panicked. So it's restarting every several minutes:

```
[2022-01-18T14:31:13Z WARN  kaspa_miner::miner] Kaspad is not synced, skipping current template
thread 'thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at '<unnamed><unnamed>called `Result::unwrap()` on an `Err` value: IllegalAddresscalled `Result::unwrap()` on an `Err` value: IllegalAddresscalled `Result::unwrap()` on an `Err` value: IllegalAddress', ' panicked at '' panicked at '', src/miner.rs', :called `Result::unwrap()` on an `Err` value: IllegalAddresscalled `Result::unwrap()` on an `Err` value: IllegalAddresssrc/miner.rssrc/miner.rs150', ', :::150src/miner.rssrc/miner.rs37150:::
:37note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
37
150150
::3737
```

Thanks to hiveos, it restarts then, but I'm probably loosing some hashrate. I observe this regardles of last 2 miner versions, as well as previous stable and current beta nvidia drivers:

Actual:
miner v0.2.1-GPU-0.3
NVIDIA-SMI 495.46       Driver Version: 495.46       CUDA Version: 11.5   
hardware: 5 x rtx 3070 ti

**Comment by twkrol** [comment]
I'm monitoring the log.
It's not always after out of sync:
`[2022-01-18T14:53:10Z INFO  kaspa_miner::miner] Current hashrate is: 2.48 Ghash/s
[2022-01-18T14:53:20Z INFO  kaspa_miner::miner] Current hashrate is: 2.48 Ghash/s
[2022-01-18T14:53:30Z INFO  kaspa_miner::miner] Current hashrate is: 2.48 Ghash/s
[2022-01-18T14:53:36Z WARN  kaspa_miner::miner] Kaspad is not synced, skipping current template
[2022-01-18T14:53:40Z INFO  kaspa_miner::miner] Current hashrate is: 2.46 Ghash/s
[2022-01-18T14:53:50Z INFO  kaspa_miner::miner] Current hashrate is: 2.48 Ghash/s
[2022-01-18T14:54:00Z INFO  kaspa_miner::miner] Current hashrate is: 2.48 Ghash/s
`

**Comment by twkrol** [comment]
Not all 'out of syncs' induces errors, but all errors are directly after that, so far.

**Comment by twkrol** [comment]
Anothe, very rare case, after sucessfull block:

```
[2022-01-18T21:17:09Z INFO  kaspa_miner::miner] Current hashrate is: 2.49 Ghash/s
[2022-01-18T21:17:10Z INFO  kaspa_miner::miner] Found a block: 3c9f960a9cb3702bb8e2f1b6246c9f1a17f9e5ed063324a171ce333bbcd3a907
[2022-01-18T21:17:10Z INFO  kaspa_miner::client] block submitted successfully!
thread 'thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: IllegalAddress<unnamed>called `Result::unwr
ap()` on an `Err` value: IllegalAddress' panicked at '<unnamed>called `Result::unwrap()` on an `Err` value: IllegalAddress', ', src/miner.rscalled `Result::unwrap()` on an `Err` value: IllegalAddress'
 panicked at '', :called `Result::unwrap()` on an `Err` value: IllegalAddresssrc/miner.rssrc/miner.rs', :', 150150:src/miner.rssrc/miner.rs:::15037:15015037::
:
37note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
3737

```

**Comment by twkrol** [comment]
I guess the problem could be because I added another card to the rig, which could not be overclocked like the others and therefore generated errors. When I lowered the timing for the whole set, there were no errors from yesterday.
Sorry if I took your time to investigate, I think this issue can be closed.

**Comment by tmrlvi** [comment]
No problem. Feel free to re-open if this issue persists
