### ISSUE TITLE
Enable cuda oc

### ISSUE THREAD

**Issue by benrod3k** [tmrlvi/kaspa-miner#20]
Lock mem-clocks help to gain some extra hashrates. To enable lock-mem-clocks in a very low value eg: absolute 810Mhz in hiveos, the user have to invoke `nvidia-smi` through a scheduled event.

In bzminer and lolminer there're parameters to lock mem clocks.  kaspa-miner should be able to do the same.

**Comment by tmrlvi** [comment]
Merged to v0.5

**Comment by tmrlvi** [comment]
Reopening:
I didn't notice, but the PR compiles only on nightly because of OneCell. How much is it necessary?

**Comment by benrod3k** [comment]
> Reopening: I didn't notice, but the PR compiles only on nightly because of OneCell. How much is it necessary?

For the current version, to introduce lock memory clocks, it's not necessary. Because only once it should be ran. 

But to keep the nvml instance somewhere to reuse, in order to report gpu status etc. It's necessary. I could revert the lasat commit though. And bring a better solution back later.

**Comment by tmrlvi** [comment]
merged
