### ISSUE TITLE
Run error in Ubuntu 20

### ISSUE THREAD

**Issue by bugxzhu** [tmrlvi/kaspa-miner#37]
ERROR kaspacuda::worker] Error loading PTX. Make sure you have the updated driver for you devices
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownError', plugins/cuda/src/lib.rs:159:18
^C

**Comment by bugxzhu** [comment]
NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4

**Comment by tmrlvi** [comment]
As it says - `Make sure you have the updated driver for you devices`
Note that some devices are locked to a minimal cuda version. https://kaspawiki.net/index.php/Mining#Nvidia_Drivers
