### ISSUE TITLE
Cargo install

### ISSUE THREAD

**Issue by sacredland** [tmrlvi/kaspa-miner#39]
unable to finish the install with cargo

sudo cargo install kaspa-miner
    Updating crates.io index
  Downloaded kaspa-miner v0.2.0
error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/kaspa-miner-0.2.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown

**Comment by tmrlvi** [comment]
Please update your rust toolchain. You can use https://rustup.rs/ for the most up to date toolchain.
