### ISSUE TITLE
Offer to add more technical info!!!

### ISSUE THREAD

**Issue by BARUCHER777** [tmrlvi/kaspa-miner#41]
I tested your software under Windows 10 Enterprise 64-bit. Everything functions relatively stably!... Alas, I don’t know if it’s normal, the hashrate is 90-92 megahash! Please complete your technical documentation. I mean, make at least a normal readme file as part of the archive, so that everyone can immediately understand what hashrate should be on different models of video cards, and from different competing manufacturers, these very video cards!

**Comment by BARUCHER777** [comment]
Video-Card Radeon RX 580. Last actual drivers for Win 10 Ent 64-bit.

**Comment by tmrlvi** [comment]
The hashrates are available in kaspa wiki https://kaspawiki.net/index.php/Hashrate_tables
This seems to be comparable to lol miner

I won't make it part of the repository as this information changes often when other miners improve and evolve.
