### ISSUE TITLE
failed to run custom build command

### ISSUE THREAD

**Issue by kenny815** [tmrlvi/kaspa-miner#44]
When I try to use cargo build --release -p kaspa-miner -p kaspacuda -p kaspaopencl to compile the code, I keep recieving this error
error: failed to run custom build command for `cust_raw v0.11.3`
Caused by:
  process didn't exit successfully: `D:\kaspa-miner-main\target\release\build\cust_raw-78d8583b1f3493ef\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Could not find a cuda installation', C:\Users\kenny\.cargo\registry\src\github.com-1ecc6299db9ec823\find_cuda_helper-0.2.0\src\lib.rs:12:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

My gcc version is 8.3.0 and I use vscode to compile.
Please help me fix it. Thanks!

**Comment by tmrlvi** [comment]
If you try to build, you need cuda toolkit. Download from here:
https://developer.nvidia.com/cuda-downloads

Note that for older miner you'll need older cuda

I need to add more explicit compiling instruction

**Comment by kenny815** [comment]
Thanks. It works.
