### ISSUE TITLE
[Feature request] Add option to GPU mining on pool

### ISSUE THREAD

**Issue by hristo-mavrodiev** [tmrlvi/kaspa-miner#45]
Hi,
Is there any way for mining on pool instead of solo mining on node?
It will be nice to have stratum+tcp:// connection for pools for small farms.

Thanks

**Comment by tmrlvi** [comment]
It is already there. For example
```
./kaspa-miner -s stratum+tcp://acc-pool.pw:16061 -a kaspa:qr36zdxs0dn3n0h799jhdl02qks5742lxjgmfsfj9xmlca7n4l6mw0s0n48nx
```

Though, I need to add it to the docs

**Comment by jasper22** [comment]
> It is already there. For example
> 
> ```
> ./kaspa-miner -s stratum+tcp://acc-pool.pw:16061 -a kaspa:qr36zdxs0dn3n0h799jhdl02qks5742lxjgmfsfj9xmlca7n4l6mw0s0n48nx
> ```
> 
> Though, I need to add it to the docs

So - in this case I don't need to download full node to my machine right ?

**Comment by tmrlvi** [comment]
No need for full node in this case
