### ISSUE TITLE
Attempting mining with openCl or no gpu 

### ISSUE THREAD

**Issue by johnnyde94** [tmrlvi/kaspa-miner#5]
Hello I currently have an all amd system and I was trying to test —openCl-device command and the —no-gpu command and I get the system error the code execution cannot proceed because nvcuda.Dll was not found. Reinstalling the program may fix the problem.

I know this is because I don’t have cuda installed but is there I way to get around it trying to use cuda altogether. I would love to be able to gpu mine with amd cards and am happy to help test. 

Thanks!

**Comment by tmrlvi** [comment]
Thanks for reporting! 
I suspect the problem is in [this line](https://github.com/tmrlvi/kaspa-miner/blob/main/src/main.rs#L36)

Can you attach the full output, so I can be sure?

**Comment by johnnyde94** [comment]
What do you mean by full output, that was the full error I had. Is there a debug or log file I can send or do you want a picture of the error?

John DeLuca

**Comment by tmrlvi** [comment]
Usually all the logs are written into the console. From your response, I can guess it was a pop-up right?

**Comment by johnnyde94** [comment]
Yep it was a pop-up it seems like the pics didn’t want to go though I’ll resend it directly though GitHub. Had to redownload the blockchain as it got corrupted after a crash lol. Didn’t take too long to get back and running. Is the actual Wallet file just the encrypted mnemonic file I saw? 
![Uploading 68EB5779-F0FA-4762-8C49-284E7AF690DF.jpeg…]()

**Comment by tmrlvi** [comment]
Solved by commit https://github.com/tmrlvi/kaspa-miner/commit/7b542f6b1183d1ccee3f229b29bd70af05816acd

**Comment by tmrlvi** [comment]
@johnnyde94  Release [v0.2.1-GPU-0.2](https://github.com/tmrlvi/kaspa-miner/releases/tag/v0.2.1-GPU-0.2) should solve the issue. Feel free to reopen the issue if it doesn't,.

**Comment by johnnyde94** [comment]
Tested and working thank you!

John DeLuca
